FROM nginx:1.27-alpine

WORKDIR /usr/share/nginx/html

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY index.html pudim.html box.html admin.html ./
COPY favicon.svg manifest.webmanifest ./
COPY *.css *.js ./
COPY assets ./assets
COPY telas ./telas

EXPOSE 80
